language: node_js
dist: trusty
node_js:
  - "8"

branches:
  only:
    - master

os:
#  - linux
  - osx

git:
  depth: false

cache:
  directories:
    - node_modules
    - $HOME/.electron

before_script:
#  - ./.travis/run-xvfb.sh
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
  - sleep 2

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - yarn --version
  - yarn test

notifications:
  email:
    on_success: never
    on_failure: change