name: Build/release

on: push
  # push:
  #   branches:
  #     - "master"

jobs:
  release:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        platform: [darwin, linux, win32]
        exclude:
          - os: macos-latest
            platform: linux
          - os: macos-latest
            platform: win32
          - os: ubuntu-latest
            platform: darwin
          - os: ubuntu-latest
            platform: win32
          - os: windows-latest
            platform: darwin
          - os: windows-latest
            platform: linux

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build distributables
        run: yarn dist-${{ matrix.platform }}