name: Build/Release

on: push
  # push:
  #   branches:
  #     - "master"

jobs:
  release:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        platform: [darwin, linux, win32]
        exclude:
          - os: macos-latest
            platform: linux
          - os: macos-latest
            platform: win32
          - os: ubuntu-latest
            platform: darwin
          - os: ubuntu-latest
            platform: win32
          - os: windows-latest
            platform: darwin
          - os: windows-latest
            platform: linux

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build distributables
        run: yarn dist-${{ matrix.platform }}

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'package.json'
            prop_path: 'version'
      - run: echo Found version ${{steps.version.outputs.prop}}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ResIDE-${{ matrix.platform }}-${{steps.version.outputs.prop}}"
          files: out/make/zip/${{ matrix.platform }}/x64/*.zip